/*
路由懒加载的好处
当打包构建应用时,JavaScript包会变得非常大,影响页面加载。
加果我们能把不同路由对应的组件分割成不同的代码块，然后当路由被访问的时候才加载对应组件，这样就更加高效了。
*/
export default [
    {
        // 路由重定向
        path:'*',
        redirect:'/home'
    },
    {
        path:'/detail/:skuid',
        component:()=>import('@/views/Detail'),
        meta:{show:true}
    },
    {
        path:'/center',
        component:()=>import('@/views/Center'),
        meta:{show:true},
        children:[
            {
                path:'myorder',
                component:()=>import('@/views/Center/myOrder')
            },
            {
                path:'groupOrder',
                component:()=>import('@/views/Center/groupOrder')
            },
            {
                path:'/center',
                redirect:'/center/myorder'
            }
        ]
    },
    {
        path:'/paysuccess',
        component:()=>import('@/views/PaySuccess'),
        meta:{show:true},
        // 路由独享守卫 
        beforeEnter:(to,from,next)=>{
            if(from.path=='/pay'){
                next()
            }else{
                next(false)
            }
        }
    },
    {
        path:'/pay',
        component:()=>import('@/views/Pay'),
        meta:{show:true},
        beforeEnter:(to,from,next)=>{
            if(from.path=='/trade'){
                next()
            }else{
                next(false)
            }
        }
    },
    {
        path:'/trade',
        component:()=>import('@/views/Trade'),
        meta:{show:true},
        beforeEnter:(to,from,next)=>{
            if(from.path=='/shopcart'){
                next()
            }else{
                next(false)
            }
        }
    },
    {
        path:'/addcartsuccess',
        name:'addcartsuccess',
        component:()=>import('@/views/AddCartSuccess'),
        meta:{show:true}
    },
    {
        path:'/shopcart',
        name:'shopcart',
        component:()=>import('@/views/ShopCart'),
        meta:{show:true}
    },
    {
        path:'/home',
        component:()=>import('@/views/Home'),
        meta:{show:true}
    },
    {
        path:'/search/:keyword?',
        name:'search',
        component:()=>import('@/views/Search'),
        meta:{show:true}
    },
    {
        path:'/login',
        component:()=>import('@/views/Login'),
        meta:{show:false}
    },
    {
        path:'/register',
        component:()=>import('@/views/Register'),
        meta:{show:false}
    },
]